[mypy]
files = romanceio, romanceio_fields, common
disallow_incomplete_defs = True
check_untyped_defs = True
ignore_missing_imports = True
exclude = (?x)(
    ^calibre[/\\]
    | ^\.romanceio[/\\]
    | [/\\]__pycache__[/\\]
    | [/\\]downloaded_files[/\\]
    | ^romanceio_fields[/\\]certifi[/\\]
    | ^romanceio_fields[/\\]colorama[/\\]
    | ^romanceio_fields[/\\]cssselect[/\\]
    | ^romanceio_fields[/\\]fake_useragent[/\\]
    | ^romanceio_fields[/\\]fasteners[/\\]
    | ^romanceio_fields[/\\]mycdp[/\\]
    | ^romanceio_fields[/\\]requests[/\\]
    | ^romanceio_fields[/\\]sbvirtualdisplay[/\\]
    | ^romanceio_fields[/\\]selenium[/\\]
    | ^romanceio_fields[/\\]seleniumbase[/\\]
    | ^romanceio_fields[/\\]urllib3[/\\]
    | ^romanceio_fields[/\\]websocket[/\\]
    | ^romanceio_fields[/\\]websockets[/\\]
    | ^romanceio_fields[/\\]Xlib[/\\]
    )
